### ISSUE TITLE
Unable to load 'gc'

### ISSUE THREAD

**Issue by kenmartin-unix** [ratboy666/fbasic#1]
Unable to compile on Ubuntu 22.04

-lgc is missing

Have added gc.h from WWW.

Thanks

**Comment by ratboy666** [comment]
Yes, fbasic uses Boehm-Demers-Weiser conservative garbage collector -- On fedora, the package is gc-devel (sudo dnf install gc-devel). What is the package for Ubuntu? I'll add to the build instructions in the source. As a note, fbasic was written as a "weekend hack" to run a chess program written in BASIC. I then spent a couple more weekends bringing it up to 80% MBASIC 5 compatibility (but, I just added zero-trip FOR loops -- I noticed I had missed that case after posting the 20 year old source).

fbasic also uses curses. On fedora, sudo dnf install ncurses-devel -- what is is on Ubuntu (no, I don't have Ubuntu).

Thanks! FredW

**Comment by kenmartin-unix** [comment]
After compiling and loading a simple program got this:
| |__   __ _ ___(_) ___ 
| '_ \ / _` / __| |/ __|
| |_) | (_| \__ \ | (__ 
|_.__/ \__,_|___/_|\___|
(c) 2015-2016 Johan Van den Brande
LOAD "FOR.BAS"
READY.
LIST <<<--- No output
 KenUnix
READY.
RUN
READY.
SYSTEM
--- ERROR: 0 UNEXPECTED SYMBOL
SHOW 10 STACK FRAMES:
  build/basic/basic(error+0x6b) [0x55ff5da8de1d]
  build/basic/basic(+0x4fd9) [0x55ff5da8ffd9]
  build/basic/basic(+0x7514) [0x55ff5da92514]
  build/basic/basic(+0x79ba) [0x55ff5da929ba]
  build/basic/basic(+0x791d) [0x55ff5da9291d]
  build/basic/basic(+0x84a4) [0x55ff5da934a4]
  build/basic/basic(+0x30da) [0x55ff5da8e0da]
  build/basic/basic(+0x3280) [0x55ff5da8e280]
  /lib/x86_64-linux-gnu/libc.so.6(+0x29d90) [0x7f71d3736d90]
  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80) [0x7f71d3736e40]
--- ERROR: 0 FACTOR SYNTAX ERROR
SHOW 10 STACK FRAMES:
  build/basic/basic(error+0x6b) [0x55ff5da8de1d]
  build/basic/basic(+0x516a) [0x55ff5da9016a]
  build/basic/basic(+0x527e) [0x55ff5da9027e]
  build/basic/basic(+0x5299) [0x55ff5da90299]
  build/basic/basic(+0x539b) [0x55ff5da9039b]
  build/basic/basic(+0x751f) [0x55ff5da9251f]
  build/basic/basic(+0x79ba) [0x55ff5da929ba]
  build/basic/basic(+0x791d) [0x55ff5da9291d]
  build/basic/basic(+0x84a4) [0x55ff5da934a4]
  build/basic/basic(+0x30da) [0x55ff5da8e0da]
ERROR: FACTOR SYNTAX ERROR

FOR.BAS contains:
100 PRINT "FOR test"
110 FOR A=0 TO 10
120 PRINT A
130 NEXT
140 PRINT "done"

**Comment by ratboy666** [comment]
Ken -- THAT is strange.
fbasic should do this:

(and note the prompt is Ok, not READY.) Looks like the signon
is trying to do something cute... in monspace. Is that BWBASIC?

: fred@llana klara $; fbasic
FBASIC 2.2
Written 2000, 2001, 2022 Fridtjof Weigel
MIT Licensed

Ok
LOAD "FOR.BAS"
Ok
LIST
     100 PRINT "FOR test"
     110 FOR A=0 TO 10
     120 PRINT A
     130 NEXT 
     140 PRINT "done"
Ok
RUN
FOR test
 0 
 1 
 2 
 3 
 4 
 5 
 6 
 7 
 8 
 9 
 10 
done
Ok
SYSTEM
: fred@llana klara $;

**Comment by kenmartin-unix** [comment]
Do you have any ideas?

**Comment by ratboy666** [comment]
Ken

Sure fbasic prompt is Ok, not READY so probably running something else! I posted on GitHub as well!


Sent from my iPhone

On Jan 31, 2023, at 11:38 AM, kenmartin-unix ***@***.***> wrote:

﻿

Do you have any ideas?

**Comment by kenmartin-unix** [comment]
This is the greeting:

| |__   __ _ ___(_) ___ 
| '_ \ / _` / __| |/ __|
| |_) | (_| \__ \ | (__ 
|_.__/ \__,_|___/_|\___|
(c) 2015-2016 Johan Van den Brande

**Comment by ratboy666** [comment]
It has been two months. Closing this.
